[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -c \"from passlib.context import CryptContext; c=CryptContext(schemes=['bcrypt']); print(c.hash('manager123')); print(c.hash('conseil123')); print(c.hash('conseil456'))\""
healthcheckPath = "/"
